default: &default
  host: <%= ENV.fetch("RDS_HOSTNAME", "localhost") %>
  adapter: postgresql
  username: <%= ENV.fetch("RDS_USERNAME", "postgres") %>
  password: <%= ENV.fetch("RDS_PASSWORD", "postgres") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  port: <%= ENV.fetch("RDS_PORT", 5432) %>
  database: <%= ENV.fetch("RDS_DB_NAME", "postgres") %>

  timeout: 5000

development:
  <<: *default
  database: development-<%= ENV.fetch("RDS_DB_NAME", "postgres") %>

test:
  <<: *default
  database: test-<%= ENV.fetch("RDS_DB_NAME", "postgres") %>
